# Base image
FROM mysql:5.7

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=zabbix
ENV MYSQL_USER=zabbix
ENV MYSQL_PASSWORD=zabbix_password


# Expose MySQL port
EXPOSE 3306 

# Start MySQL server and keep running
CMD ["mysqld"]
		