{
 "title": "Turbine",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Turbine Status",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "speed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:speed.high",
     "timeField": "@timestamp"
    },
    {
     "alias": "feathered",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:feathered",
     "timeField": "@timestamp"
    },
    {
     "alias": "mw",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:turbine.mw-output",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Output",
   "type": "timeseries",
   "description": "Power Output over time",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "turbine.mw-output",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:pressure",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:speed.high",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wind Speed At Different Heights",
   "type": "timeseries",
   "description": "Wind Speed at 58.2m, 36.6m, and 15m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "High: 58.2m",
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "speed.high",
     "timeField": "@timestamp"
    },
    {
     "alias": "Med: 36.6m",
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "speed.med",
     "timeField": "@timestamp"
    },
    {
     "alias": "Low: 15m",
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "speed.low",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Yaw Current",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "yaw.current",
     "timeField": "@timestamp"
    },
    {
     "alias": "Yaw Setpoint",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "yaw.setpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Temp. (High)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:temp.high",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wind Direction (High)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "field:dir.high",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blade-1 Feathered Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "blade-1.feathered",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blade-2 Feathered Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "blade-2.feathered",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blade-3 Feathered Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "blade-3.feathered",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Emergency Stop",
   "type": "stat",
   "description": "Emergency Stop Indication\nGreen - Running Normally (0)\nRed - Emergency Stop active (1)",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "turbine.emergency-stop",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}